modLoader="javafml"
loaderVersion="[36,)"
license="All Rights Reserved"

[[mods]]
modId="hollowknightmod"
version="${file.jarVersion}"
displayName="Hollow Knight Mod"
logoFile="old_nail.png"
logoBlur=false
credits="Hollow Knight was created by Team Cherry. Mod art and development by Kayk Caputo."
authors="Kayk Caputo"
description='''
An unofficial fan-made Minecraft Forge mod inspired by Hollow Knight.

Explore the world for naturally generated Pale Ore, forge new materials,
wield the Old Nail, wear the Knight armor set with 3D horns, and discover
other Hallownest-inspired content.
'''

[[dependencies.hollowknightmod]]
modId="forge"
mandatory=true
versionRange="[36.2.34,)"
ordering="NONE"
side="BOTH"

[[dependencies.hollowknightmod]]
modId="minecraft"
mandatory=true
versionRange="[1.16.5,1.17)"
ordering="NONE"
side="BOTH"
